#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=\
    liferay-adyen-payment-integration-oauth-application-user-agent,\
    liferay-adyen-payment-integration-oauth-application-headless-server

liferay.oauth.urls.excludes=\
    /ready,\
    /notifications

#
# Spring Boot
#

server.port=58081