/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.discount.service.base;

import com.liferay.commerce.discount.model.CommerceDiscountEntryCheck;
import com.liferay.commerce.discount.service.CommerceDiscountEntryCheckLocalService;
import com.liferay.commerce.discount.service.CommerceDiscountEntryCheckLocalServiceUtil;
import com.liferay.commerce.discount.service.persistence.CommerceDiscountEntryCheckPersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the commerce discount entry check local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.commerce.discount.service.impl.CommerceDiscountEntryCheckLocalServiceImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see com.liferay.commerce.discount.service.impl.CommerceDiscountEntryCheckLocalServiceImpl
 * @generated
 */
public abstract class CommerceDiscountEntryCheckLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CommerceDiscountEntryCheckLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CommerceDiscountEntryCheckLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CommerceDiscountEntryCheckLocalServiceUtil</code>.
	 */

	/**
	 * Adds the commerce discount entry check to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceDiscountEntryCheckLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceDiscountEntryCheck the commerce discount entry check
	 * @return the commerce discount entry check that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CommerceDiscountEntryCheck addCommerceDiscountEntryCheck(
		CommerceDiscountEntryCheck commerceDiscountEntryCheck) {

		commerceDiscountEntryCheck.setNew(true);

		return commerceDiscountEntryCheckPersistence.update(
			commerceDiscountEntryCheck);
	}

	/**
	 * Creates a new commerce discount entry check with the primary key. Does not add the commerce discount entry check to the database.
	 *
	 * @param commerceDiscountEntryCheckId the primary key for the new commerce discount entry check
	 * @return the new commerce discount entry check
	 */
	@Override
	@Transactional(enabled = false)
	public CommerceDiscountEntryCheck createCommerceDiscountEntryCheck(
		long commerceDiscountEntryCheckId) {

		return commerceDiscountEntryCheckPersistence.create(
			commerceDiscountEntryCheckId);
	}

	/**
	 * Deletes the commerce discount entry check with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceDiscountEntryCheckLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceDiscountEntryCheckId the primary key of the commerce discount entry check
	 * @return the commerce discount entry check that was removed
	 * @throws PortalException if a commerce discount entry check with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CommerceDiscountEntryCheck deleteCommerceDiscountEntryCheck(
			long commerceDiscountEntryCheckId)
		throws PortalException {

		return commerceDiscountEntryCheckPersistence.remove(
			commerceDiscountEntryCheckId);
	}

	/**
	 * Deletes the commerce discount entry check from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceDiscountEntryCheckLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceDiscountEntryCheck the commerce discount entry check
	 * @return the commerce discount entry check that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CommerceDiscountEntryCheck deleteCommerceDiscountEntryCheck(
		CommerceDiscountEntryCheck commerceDiscountEntryCheck) {

		return commerceDiscountEntryCheckPersistence.remove(
			commerceDiscountEntryCheck);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return commerceDiscountEntryCheckPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CommerceDiscountEntryCheck.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return commerceDiscountEntryCheckPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.discount.model.impl.CommerceDiscountEntryCheckModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return commerceDiscountEntryCheckPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.discount.model.impl.CommerceDiscountEntryCheckModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return commerceDiscountEntryCheckPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return commerceDiscountEntryCheckPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return commerceDiscountEntryCheckPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CommerceDiscountEntryCheck fetchCommerceDiscountEntryCheck(
		long commerceDiscountEntryCheckId) {

		return commerceDiscountEntryCheckPersistence.fetchByPrimaryKey(
			commerceDiscountEntryCheckId);
	}

	/**
	 * Returns the commerce discount entry check with the primary key.
	 *
	 * @param commerceDiscountEntryCheckId the primary key of the commerce discount entry check
	 * @return the commerce discount entry check
	 * @throws PortalException if a commerce discount entry check with the primary key could not be found
	 */
	@Override
	public CommerceDiscountEntryCheck getCommerceDiscountEntryCheck(
			long commerceDiscountEntryCheckId)
		throws PortalException {

		return commerceDiscountEntryCheckPersistence.findByPrimaryKey(
			commerceDiscountEntryCheckId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			commerceDiscountEntryCheckLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CommerceDiscountEntryCheck.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceDiscountEntryCheckId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			commerceDiscountEntryCheckLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			CommerceDiscountEntryCheck.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceDiscountEntryCheckId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			commerceDiscountEntryCheckLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CommerceDiscountEntryCheck.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"commerceDiscountEntryCheckId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return commerceDiscountEntryCheckPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement CommerceDiscountEntryCheckLocalServiceImpl#deleteCommerceDiscountEntryCheck(CommerceDiscountEntryCheck) to avoid orphaned data");
		}

		return commerceDiscountEntryCheckLocalService.
			deleteCommerceDiscountEntryCheck(
				(CommerceDiscountEntryCheck)persistedModel);
	}

	@Override
	public BasePersistence<CommerceDiscountEntryCheck> getBasePersistence() {
		return commerceDiscountEntryCheckPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return commerceDiscountEntryCheckPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the commerce discount entry checks.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.commerce.discount.model.impl.CommerceDiscountEntryCheckModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of commerce discount entry checks
	 * @param end the upper bound of the range of commerce discount entry checks (not inclusive)
	 * @return the range of commerce discount entry checks
	 */
	@Override
	public List<CommerceDiscountEntryCheck> getCommerceDiscountEntryChecks(
		int start, int end) {

		return commerceDiscountEntryCheckPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of commerce discount entry checks.
	 *
	 * @return the number of commerce discount entry checks
	 */
	@Override
	public int getCommerceDiscountEntryChecksCount() {
		return commerceDiscountEntryCheckPersistence.countAll();
	}

	/**
	 * Updates the commerce discount entry check in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CommerceDiscountEntryCheckLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param commerceDiscountEntryCheck the commerce discount entry check
	 * @return the commerce discount entry check that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CommerceDiscountEntryCheck updateCommerceDiscountEntryCheck(
		CommerceDiscountEntryCheck commerceDiscountEntryCheck) {

		return commerceDiscountEntryCheckPersistence.update(
			commerceDiscountEntryCheck);
	}

	@Deactivate
	protected void deactivate() {
		CommerceDiscountEntryCheckLocalServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CommerceDiscountEntryCheckLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		commerceDiscountEntryCheckLocalService =
			(CommerceDiscountEntryCheckLocalService)aopProxy;

		CommerceDiscountEntryCheckLocalServiceUtil.setService(
			commerceDiscountEntryCheckLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CommerceDiscountEntryCheckLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CommerceDiscountEntryCheck.class;
	}

	protected String getModelClassName() {
		return CommerceDiscountEntryCheck.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				commerceDiscountEntryCheckPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected CommerceDiscountEntryCheckLocalService
		commerceDiscountEntryCheckLocalService;

	@Reference
	protected CommerceDiscountEntryCheckPersistence
		commerceDiscountEntryCheckPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		CommerceDiscountEntryCheckLocalServiceBaseImpl.class);

}