/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.discount.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommerceDiscountEntryCheck service. Represents a row in the &quot;CommerceDiscountEntryCheck&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.commerce.discount.model.impl.CommerceDiscountEntryCheckModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.commerce.discount.model.impl.CommerceDiscountEntryCheckImpl</code>.
 * </p>
 *
 * @author Marco Leo
 * @see CommerceDiscountEntryCheck
 * @generated
 */
@ProviderType
public interface CommerceDiscountEntryCheckModel
	extends AuditedModel, BaseModel<CommerceDiscountEntryCheck>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce discount entry check model instance should use the {@link CommerceDiscountEntryCheck} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce discount entry check.
	 *
	 * @return the primary key of this commerce discount entry check
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce discount entry check.
	 *
	 * @param primaryKey the primary key of this commerce discount entry check
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this commerce discount entry check.
	 *
	 * @return the mvcc version of this commerce discount entry check
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this commerce discount entry check.
	 *
	 * @param mvccVersion the mvcc version of this commerce discount entry check
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the commerce discount entry check ID of this commerce discount entry check.
	 *
	 * @return the commerce discount entry check ID of this commerce discount entry check
	 */
	public long getCommerceDiscountEntryCheckId();

	/**
	 * Sets the commerce discount entry check ID of this commerce discount entry check.
	 *
	 * @param commerceDiscountEntryCheckId the commerce discount entry check ID of this commerce discount entry check
	 */
	public void setCommerceDiscountEntryCheckId(
		long commerceDiscountEntryCheckId);

	/**
	 * Returns the company ID of this commerce discount entry check.
	 *
	 * @return the company ID of this commerce discount entry check
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce discount entry check.
	 *
	 * @param companyId the company ID of this commerce discount entry check
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce discount entry check.
	 *
	 * @return the user ID of this commerce discount entry check
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce discount entry check.
	 *
	 * @param userId the user ID of this commerce discount entry check
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce discount entry check.
	 *
	 * @return the user uuid of this commerce discount entry check
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce discount entry check.
	 *
	 * @param userUuid the user uuid of this commerce discount entry check
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce discount entry check.
	 *
	 * @return the user name of this commerce discount entry check
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce discount entry check.
	 *
	 * @param userName the user name of this commerce discount entry check
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce discount entry check.
	 *
	 * @return the create date of this commerce discount entry check
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce discount entry check.
	 *
	 * @param createDate the create date of this commerce discount entry check
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce discount entry check.
	 *
	 * @return the modified date of this commerce discount entry check
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce discount entry check.
	 *
	 * @param modifiedDate the modified date of this commerce discount entry check
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the commerce account ID of this commerce discount entry check.
	 *
	 * @return the commerce account ID of this commerce discount entry check
	 */
	public long getCommerceAccountId();

	/**
	 * Sets the commerce account ID of this commerce discount entry check.
	 *
	 * @param commerceAccountId the commerce account ID of this commerce discount entry check
	 */
	public void setCommerceAccountId(long commerceAccountId);

	/**
	 * Returns the commerce discount ID of this commerce discount entry check.
	 *
	 * @return the commerce discount ID of this commerce discount entry check
	 */
	public long getCommerceDiscountId();

	/**
	 * Sets the commerce discount ID of this commerce discount entry check.
	 *
	 * @param commerceDiscountId the commerce discount ID of this commerce discount entry check
	 */
	public void setCommerceDiscountId(long commerceDiscountId);

	@Override
	public CommerceDiscountEntryCheck cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}