/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.commerce.discount.model.impl;

import com.liferay.commerce.discount.model.CommerceDiscountEntryCheck;
import com.liferay.commerce.discount.model.CommerceDiscountEntryCheckModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommerceDiscountEntryCheck service. Represents a row in the &quot;CommerceDiscountEntryCheck&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommerceDiscountEntryCheckModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommerceDiscountEntryCheckImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CommerceDiscountEntryCheckImpl
 * @generated
 */
public class CommerceDiscountEntryCheckModelImpl
	extends BaseModelImpl<CommerceDiscountEntryCheck>
	implements CommerceDiscountEntryCheckModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commerce discount entry check model instance should use the <code>CommerceDiscountEntryCheck</code> interface instead.
	 */
	public static final String TABLE_NAME = "CommerceDiscountEntryCheck";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"commerceDiscountEntryCheckId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"commerceAccountId", Types.BIGINT},
		{"commerceDiscountId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceDiscountEntryCheckId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("commerceAccountId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("commerceDiscountId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CommerceDiscountEntryCheck (mvccVersion LONG default 0 not null,commerceDiscountEntryCheckId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,commerceAccountId LONG,commerceDiscountId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table CommerceDiscountEntryCheck";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commerceDiscountEntryCheck.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CommerceDiscountEntryCheck.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCEACCOUNTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMMERCEDISCOUNTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommerceDiscountEntryCheckModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _commerceDiscountEntryCheckId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCommerceDiscountEntryCheckId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _commerceDiscountEntryCheckId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommerceDiscountEntryCheck.class;
	}

	@Override
	public String getModelClassName() {
		return CommerceDiscountEntryCheck.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommerceDiscountEntryCheck, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommerceDiscountEntryCheck, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceDiscountEntryCheck, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(CommerceDiscountEntryCheck)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommerceDiscountEntryCheck, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommerceDiscountEntryCheck, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommerceDiscountEntryCheck)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommerceDiscountEntryCheck, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommerceDiscountEntryCheck, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<CommerceDiscountEntryCheck, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<CommerceDiscountEntryCheck, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<CommerceDiscountEntryCheck, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CommerceDiscountEntryCheck::getMvccVersion);
			attributeGetterFunctions.put(
				"commerceDiscountEntryCheckId",
				CommerceDiscountEntryCheck::getCommerceDiscountEntryCheckId);
			attributeGetterFunctions.put(
				"companyId", CommerceDiscountEntryCheck::getCompanyId);
			attributeGetterFunctions.put(
				"userId", CommerceDiscountEntryCheck::getUserId);
			attributeGetterFunctions.put(
				"userName", CommerceDiscountEntryCheck::getUserName);
			attributeGetterFunctions.put(
				"createDate", CommerceDiscountEntryCheck::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CommerceDiscountEntryCheck::getModifiedDate);
			attributeGetterFunctions.put(
				"commerceAccountId",
				CommerceDiscountEntryCheck::getCommerceAccountId);
			attributeGetterFunctions.put(
				"commerceDiscountId",
				CommerceDiscountEntryCheck::getCommerceDiscountId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<CommerceDiscountEntryCheck, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CommerceDiscountEntryCheck, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<CommerceDiscountEntryCheck, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CommerceDiscountEntryCheck, Long>)
					CommerceDiscountEntryCheck::setMvccVersion);
			attributeSetterBiConsumers.put(
				"commerceDiscountEntryCheckId",
				(BiConsumer<CommerceDiscountEntryCheck, Long>)
					CommerceDiscountEntryCheck::
						setCommerceDiscountEntryCheckId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CommerceDiscountEntryCheck, Long>)
					CommerceDiscountEntryCheck::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CommerceDiscountEntryCheck, Long>)
					CommerceDiscountEntryCheck::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CommerceDiscountEntryCheck, String>)
					CommerceDiscountEntryCheck::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CommerceDiscountEntryCheck, Date>)
					CommerceDiscountEntryCheck::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CommerceDiscountEntryCheck, Date>)
					CommerceDiscountEntryCheck::setModifiedDate);
			attributeSetterBiConsumers.put(
				"commerceAccountId",
				(BiConsumer<CommerceDiscountEntryCheck, Long>)
					CommerceDiscountEntryCheck::setCommerceAccountId);
			attributeSetterBiConsumers.put(
				"commerceDiscountId",
				(BiConsumer<CommerceDiscountEntryCheck, Long>)
					CommerceDiscountEntryCheck::setCommerceDiscountId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCommerceDiscountEntryCheckId() {
		return _commerceDiscountEntryCheckId;
	}

	@Override
	public void setCommerceDiscountEntryCheckId(
		long commerceDiscountEntryCheckId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceDiscountEntryCheckId = commerceDiscountEntryCheckId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCommerceAccountId() {
		return _commerceAccountId;
	}

	@Override
	public void setCommerceAccountId(long commerceAccountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceAccountId = commerceAccountId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommerceAccountId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commerceAccountId"));
	}

	@Override
	public long getCommerceDiscountId() {
		return _commerceDiscountId;
	}

	@Override
	public void setCommerceDiscountId(long commerceDiscountId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_commerceDiscountId = commerceDiscountId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCommerceDiscountId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("commerceDiscountId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CommerceDiscountEntryCheck.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommerceDiscountEntryCheck toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommerceDiscountEntryCheck>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommerceDiscountEntryCheckImpl commerceDiscountEntryCheckImpl =
			new CommerceDiscountEntryCheckImpl();

		commerceDiscountEntryCheckImpl.setMvccVersion(getMvccVersion());
		commerceDiscountEntryCheckImpl.setCommerceDiscountEntryCheckId(
			getCommerceDiscountEntryCheckId());
		commerceDiscountEntryCheckImpl.setCompanyId(getCompanyId());
		commerceDiscountEntryCheckImpl.setUserId(getUserId());
		commerceDiscountEntryCheckImpl.setUserName(getUserName());
		commerceDiscountEntryCheckImpl.setCreateDate(getCreateDate());
		commerceDiscountEntryCheckImpl.setModifiedDate(getModifiedDate());
		commerceDiscountEntryCheckImpl.setCommerceAccountId(
			getCommerceAccountId());
		commerceDiscountEntryCheckImpl.setCommerceDiscountId(
			getCommerceDiscountId());

		commerceDiscountEntryCheckImpl.resetOriginalValues();

		return commerceDiscountEntryCheckImpl;
	}

	@Override
	public CommerceDiscountEntryCheck cloneWithOriginalValues() {
		CommerceDiscountEntryCheckImpl commerceDiscountEntryCheckImpl =
			new CommerceDiscountEntryCheckImpl();

		commerceDiscountEntryCheckImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		commerceDiscountEntryCheckImpl.setCommerceDiscountEntryCheckId(
			this.<Long>getColumnOriginalValue("commerceDiscountEntryCheckId"));
		commerceDiscountEntryCheckImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		commerceDiscountEntryCheckImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		commerceDiscountEntryCheckImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		commerceDiscountEntryCheckImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		commerceDiscountEntryCheckImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		commerceDiscountEntryCheckImpl.setCommerceAccountId(
			this.<Long>getColumnOriginalValue("commerceAccountId"));
		commerceDiscountEntryCheckImpl.setCommerceDiscountId(
			this.<Long>getColumnOriginalValue("commerceDiscountId"));

		return commerceDiscountEntryCheckImpl;
	}

	@Override
	public int compareTo(
		CommerceDiscountEntryCheck commerceDiscountEntryCheck) {

		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), commerceDiscountEntryCheck.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommerceDiscountEntryCheck)) {
			return false;
		}

		CommerceDiscountEntryCheck commerceDiscountEntryCheck =
			(CommerceDiscountEntryCheck)object;

		long primaryKey = commerceDiscountEntryCheck.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommerceDiscountEntryCheck> toCacheModel() {
		CommerceDiscountEntryCheckCacheModel
			commerceDiscountEntryCheckCacheModel =
				new CommerceDiscountEntryCheckCacheModel();

		commerceDiscountEntryCheckCacheModel.mvccVersion = getMvccVersion();

		commerceDiscountEntryCheckCacheModel.commerceDiscountEntryCheckId =
			getCommerceDiscountEntryCheckId();

		commerceDiscountEntryCheckCacheModel.companyId = getCompanyId();

		commerceDiscountEntryCheckCacheModel.userId = getUserId();

		commerceDiscountEntryCheckCacheModel.userName = getUserName();

		String userName = commerceDiscountEntryCheckCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commerceDiscountEntryCheckCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commerceDiscountEntryCheckCacheModel.createDate =
				createDate.getTime();
		}
		else {
			commerceDiscountEntryCheckCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commerceDiscountEntryCheckCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			commerceDiscountEntryCheckCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commerceDiscountEntryCheckCacheModel.commerceAccountId =
			getCommerceAccountId();

		commerceDiscountEntryCheckCacheModel.commerceDiscountId =
			getCommerceDiscountId();

		return commerceDiscountEntryCheckCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommerceDiscountEntryCheck, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommerceDiscountEntryCheck, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommerceDiscountEntryCheck, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CommerceDiscountEntryCheck)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, CommerceDiscountEntryCheck>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						CommerceDiscountEntryCheck.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _commerceDiscountEntryCheckId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _commerceAccountId;
	private long _commerceDiscountId;

	public <T> T getColumnValue(String columnName) {
		Function<CommerceDiscountEntryCheck, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CommerceDiscountEntryCheck)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"commerceDiscountEntryCheckId", _commerceDiscountEntryCheckId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("commerceAccountId", _commerceAccountId);
		_columnOriginalValues.put("commerceDiscountId", _commerceDiscountId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("commerceDiscountEntryCheckId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("commerceAccountId", 128L);

		columnBitmasks.put("commerceDiscountId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CommerceDiscountEntryCheck _escapedModel;

}